<script>
  export let settingsBusy = false;
  export let theme = "dark";
  export let selectedQuality = "balanced";
  export let audioMode = "source";
  export let buttonColor = "";
  export let inputBackgroundColor = "";
  export let backgroundColor = "";
  export let onSave = () => {};
</script>

<form class="settings-card" on:submit|preventDefault={onSave}><div class="settings-card-heading"><div><p class="eyebrow">preferências</p><h2>Seu jeito de usar o Telai</h2><p class="muted">Preferências ficam associadas à sua conta e acompanham você.</p></div><button class="primary rounded-xl px-4 py-2 text-xs font-extrabold" type="submit" disabled={settingsBusy}>Salvar preferências</button></div><div class="settings-form-grid"><label>Tema<select class="settings-input" bind:value={theme}><option value="dark">Escuro</option><option value="light">Claro</option></select></label><label>Qualidade padrão da transmissão<select class="settings-input" bind:value={selectedQuality}><option value="economy">Econômica · 540p</option><option value="balanced">Equilibrada · 720p</option><option value="high">Alta · 1080p</option></select></label><label>Áudio padrão<select class="settings-input" bind:value={audioMode}><option value="source">Janela ou aba escolhida</option><option value="system">Computador inteiro</option></select></label></div><div class="appearance-settings"><div><p class="settings-label">Personalização visual</p><p class="muted appearance-settings-help">Escolha as cores principais do Telai. A mudança aparece na hora e fica salva na sua conta.</p></div><div class="appearance-color-grid"><label class="appearance-color-field"><span><strong>Cor dos botões</strong><small>Ações e destaques</small></span><input type="color" bind:value={buttonColor} aria-label="Cor dos botões" /></label><label class="appearance-color-field"><span><strong>Fundo dos campos</strong><small>Inputs, buscas e seleções</small></span><input type="color" bind:value={inputBackgroundColor} aria-label="Fundo dos campos digitáveis" /></label><label class="appearance-color-field"><span><strong>Background geral</strong><small>Fundo principal da janela</small></span><input type="color" bind:value={backgroundColor} aria-label="Background geral" /></label></div><div class="appearance-preview"><span class="appearance-preview-label">Prévia</span><button class="primary appearance-preview-button" type="button" style={`background:${buttonColor};border-color:${buttonColor}`}>Botão principal</button><input class="settings-input appearance-preview-input" value="Campo digitável" readonly style={`background:${inputBackgroundColor}`} /><span class="appearance-preview-swatch" style={`background:${backgroundColor}`}>background</span></div></div></form>
